[tool.poetry]
name = "hyperspacekitchen king"
version = "0.1.0"
description = "A BL thread marketing website"
authors = ["Gulshanbyte"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^3.0.3"
Flask-SQLAlchemy = "^3.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
